const parseJsValue = require('./jsvalueparser.js');
const { now, value } = require('streamer');

// The protocol defines messages which are pieces of information exchanged between Inspector and unweave or generated by user input.

// # Common Message Processing
// ## Extract Messages From The Stream
function message(stream) {
  return JSON.parse(value(now(stream)));
}

// ## Classify Inspector Messages 
function isMethod(message, methodName) {
  return message.hasOwnProperty("method") && message.method === methodName;
}

function isResult(message, resultName) {
  return message.hasOwnProperty("result") && message.result.hasOwnProperty(resultName);
}

// ## Location In Script Source
function makeLocation(scriptHandle, lineNumber, columnNumber) {
  return [scriptHandle, lineNumber, columnNumber];
}

function makeLocationFromInspectorLocation(inspectorLocation) {
  return [inspectorLocation.scriptId, inspectorLocation.lineNumber, inspectorLocation.columnNumber];
}

function scriptHandle(location) {
  return location[0];
}

function lineNumber(location) {
  return location[1];
}

function columnNumber(location) {
  return location[2];
}

// # Message Types
// ## Captures
// Once activated, a capture aggregates all subsequent user inputs to form a value. The final useful value can be retrieved when the capture ends.
function makeCapture(category, value) {
  return JSON.stringify(Object.fromEntries([[category, value], ["ended", false]]));
}

function endCapture(captureString) {
  return (capture => {
    capture.ended = true;
   
    return JSON.stringify(capture);
  })(JSON.parse(captureString));
}

function hasEnded(message) {
  return message.hasOwnProperty("ended") && message.ended;
}

// ### Breakpoint Capture
function makeBreakpointCapture(capture) {
  return makeCapture("breakpoint", capture ? capture : "");
}

function isBreakpointCapture(message) {
  return message.hasOwnProperty("breakpoint");
}

function breakpointCapture(message) {
  return message.breakpoint;
}

function breakpointLine(message) {
  return Number(breakpointCapture(message));
}

function sendSetBreakpoint(send, scriptHandle, breakpointLine) {
  send("Debugger.setBreakpoint", {location: {scriptId: scriptHandle, lineNumber: breakpointLine}});
}

// ### Query Capture
function makeQueryCapture(capture) {
  return makeCapture("query", capture ? capture : "");
}

function isQueryCapture(message) {
  return message.hasOwnProperty("query");
}

function query(message) {
  return message.query;
}

// ## Debugger Enabled
function isDebuggerEnabled(message) {
  return isResult(message, "debuggerId");
}

function sendEnableDebugger(send) {
  send("Debugger.enable", {}); 
}

function sendStartRun(send) {
  send("Runtime.runIfWaitingForDebugger", {}); 
}

// ## Debugger Paused
function isDebuggerPaused(message) {
  return isMethod(message, "Debugger.paused");
}

function pauseLocation(message) {
  return makeLocationFromInspectorLocation(message.params.callFrames[0].location);
}

function sendContinue(send) {
  send("Debugger.resume", {});
}

function sendStepInto(send) {
  send("Debugger.stepInto", {});
}

function sendStepOut(send) {
  send("Debugger.stepOut", {});
}

function sendStepOver(send) {
  send("Debugger.stepOver", {});
}

// ## Environment
function isEnvironment(message) {
  return isResult(message, "result") && message.id === 0;
}

function isEnvironmentEntry(message) {
  return isResult(message, "result") && message.id !== 0;
}

function readEnvironment(message) {
  return message.result.result.filter(entry => {
    return !(name(entry) === "exports" || name(entry) === "require" || name(entry) === "module"
	     || name(entry) === "__filename" || name(entry) === "__dirname");
  });
}

function readEnvironmentEntryUniqueId(message) {
  return message.id;
}

function entryUniqueId(entry) {
  return (({injectedScriptId, id}) => Number(`${injectedScriptId}0${id}`))(remoteHandle(entry));
}

function entryValue(entry) {
  return (entry.value.type === "string" ? value => `\"${value}\"` :  value => value)(entry.value.value)
}

function name(entry) {
  return entry.name;
}

function remoteHandle(entry) {
  return JSON.parse(entry.value.objectId);
}

function type(entry) {
  const capitalizeName = name => name.charAt(0).toUpperCase() + name.slice(1);

  if (entry.value.type === "object" || entry.value.type === "function") {
    if (entry.value.subtype === "null" || entry.value.subtype === "proxy") {
      return capitalizeName(entry.value.subtype);
    }
    else {
      return entry.value.className;
    }
  }
  else {
    return capitalizeName(entry.value.type);
  }
}

function sendRequestForEnvironmentDescription(send, message) {
  send("Runtime.getProperties", {objectId: message.params.callFrames[0].scopeChain[0].object.objectId});
}

function sendRequestForEnvironmentEntryDescription(send, entry) {
  send("Runtime.getProperties", {objectId: JSON.stringify(remoteHandle(entry))}, entryUniqueId(entry));
}

// ## Environment Tree
function makeEnvironmentTreeMessage(environmentTree) {
  return JSON.stringify({environmentTree: environmentTree});
}

function isEnvironmentTree(message) {
  return message.hasOwnProperty("environmentTree");
}

function readEnvironmentTree(message) {
  return message.environmentTree;
}

// ## Error
function makeError(reason) {
  return JSON.stringify({error: reason});
}

function isError(message) {
  return message.hasOwnProperty("error");
}

function reason(message) {
  return message.error;
}

// ## Execution Context Created
function isExecutionContextCreated(message) {
  return isMethod(message, "Runtime.executionContextCreated");
}

function sendEnableRuntime(send) {
  send("Runtime.enable", {}); 
}

// ## Focuses
// While activated, a focus attributes each user input to a specified category.

// ### Environment Tree Focus
function makeEnvironmentTreeFocus(capture) {
  return makeCapture("focusEnvironmentTree", capture ? capture : "");
}

function isEnvironmentTreeFocus(message) {
  return message.hasOwnProperty("focusEnvironmentTree");
}

function environmentTreeFocusInput(message) {
  return message.focusEnvironmentTree;
}

// ### Messages Focus
function makeMessagesFocus(capture) {
  return makeCapture("focusMessages", capture ? capture : "");
}

function isMessagesFocus(message) {
  return message.hasOwnProperty("focusMessages");
}

function messagesFocusInput(message) {
  return message.focusMessages;
}

// ### Source Tree Focus
function makeSourceTreeFocus(capture) {
  return makeCapture("focusSourceTree", capture ? capture : "");
}

function isSourceTreeFocus(message) {
  return message.hasOwnProperty("focusSourceTree");
}

function sourceTreeFocusInput(message) {
  return message.focusSourceTree;
}

// ## Input
function makeInput(key) {
  return JSON.stringify({input: key});
}
function isInput(message) {
  return message.hasOwnProperty("input");
}

function input(message) {
  return message.input;
}

function interactionKeys(interaction) {
  switch (interaction) {
    case "stepOver": return "n";
    case "stepInto": return "s";
    case "stepOut": return "f";
    case "continue": return "c";
    case "scrollDown": return "j";
    case "scrollUp": return "k";
    case "selectNext": return "j";
    case "selectPrevious": return "k";
    case "selectChild": return "l";
    case "selectParent": return "h";
    case "breakpointCapture": return "b";
    case "queryCapture": return "q";
    case "environmentTreeFocus": return "e";
    case "sourceTreeFocus": return "w";
    case "messagesFocus": return "m";
    default: throw "invalid interaction";
  };
}

// ## Inspector Query
function makeInspectorQuery(method, parameters, requestId) {
  return JSON.stringify({method: method, params: parameters, id: requestId ? requestId : 0})
}

function parseInspectorQuery(line) {
  const [method, parameters] = line.match(/^([^\s]+)|[^\1]+/g);

  return [method, parseJsValue(parameters ? parameters : "")];
}

function sendQuery(send, message) {
  send(...parseInspectorQuery(query(message)));
}

// ## Script Parsed
function isScriptParsed(message) {
  return isMethod(message, "Debugger.scriptParsed");
}

function isUserScriptParsed(message) {
  return isScriptParsed(message) && parsedScriptUrl(message).startsWith("file://");
}

function parsedScriptHandle(message) {
  return message.params.scriptId;
}

function parsedScriptUrl(message) {
  return message.params.url;
}

function parsedUserScriptPath(message) {
  return parsedScriptUrl(message).slice("file://".length);
}

// ## Script Source
function isScriptSource(message) {
  return isResult(message, "scriptSource");
}

function readScriptSource(message) {
  return message.result.scriptSource.trim();
}

function sendRequestForScriptSource(send, scriptHandle) {
  send("Debugger.getScriptSource", {scriptId: scriptHandle});
}

// ## Source Tree
function makeSourceTreeMessage(sourceTree) {
  return JSON.stringify({sourceTree: sourceTree});
}

function isSourceTree(message) {
  return message.hasOwnProperty("sourceTree");
}

function readSourceTree(message) {
  return message.sourceTree;
}

module.exports = {
  breakpointCapture,
  breakpointLine,
  columnNumber,
  endCapture,
  entryUniqueId,
  entryValue,
  environmentTreeFocusInput,
  hasEnded,
  input,
  interactionKeys,
  isBreakpointCapture,
  isDebuggerEnabled,
  isDebuggerPaused,
  isEnvironment,
  isEnvironmentEntry,
  isEnvironmentTree,
  isEnvironmentTreeFocus,
  isError,
  isExecutionContextCreated,
  isInput,
  isMessagesFocus,
  isQueryCapture,
  isScriptParsed,
  isScriptSource,
  isSourceTree,
  isSourceTreeFocus,
  isUserScriptParsed,
  lineNumber,
  makeBreakpointCapture,
  makeEnvironmentTreeFocus,
  makeEnvironmentTreeMessage,
  makeError,
  makeInput,
  makeInspectorQuery,
  makeLocation,
  makeMessagesFocus,
  makeQueryCapture,
  makeSourceTreeFocus,
  makeSourceTreeMessage,
  message,
  messagesFocusInput,
  name,
  parsedScriptHandle,
  parsedScriptUrl,
  parsedUserScriptPath,
  pauseLocation,
  query,
  readEnvironment,
  readEnvironmentEntryUniqueId,
  readEnvironmentTree,
  readScriptSource,
  readSourceTree,
  reason,
  scriptHandle,
  sendContinue,
  sendEnableDebugger,
  sendEnableRuntime,
  sendQuery,
  sendRequestForEnvironmentDescription,
  sendRequestForEnvironmentEntryDescription,
  sendRequestForScriptSource,
  sendSetBreakpoint,
  sendStartRun,
  sendStepInto,
  sendStepOut,
  sendStepOver,
  sourceTreeFocusInput,
  type
};
